# Generated by Django 2.2.7 on 2020-02-08 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('open_status', models.BooleanField(default=False)),
                ('hardware', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_adress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.Lock')),
            ],
        ),
    ]
